Create code.cs
circumstancesl/Input_output_Lab pull request #1
Opened 2024-02-28 13:30 UTC by circumstancesl

2024-02-28 15:07 UTC, KitovDanil requested changes

2024-02-28 15:07 UTC, KitovDanil commented on code.cs
> +    public void Save(string FilePath)
Помимо XML сериализации, по заданию нужно сделать ещё и бинарную, а пользователю дать возможность выбирать.

2024-02-28 15:07 UTC, KitovDanil commented on code.cs
> +    public TextFile(string FilePath)
Аргументы методов используют lowerCamelCase.
https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/identifier-names
![image](https://github.com/circumstancesl/Input_output_Lab/assets/8685613/07f9381f-dbce-4249-822d-4c49d64f5f67)

2024-02-28 15:07 UTC, KitovDanil commented on code.cs
> +        FilePath = FilePath;
Может, this.FilePath = FilePath?

2024-02-28 15:07 UTC, KitovDanil commented on code.cs
> +        using (var Writer = new StreamWriter(FilePath))
Локальные переменные используют lowerCamelCase (см. скрин и ссылку выше).

Ниже есть подобные ошибки, не буду писать комментарий к каждой.

2024-02-28 15:07 UTC, KitovDanil commented on code.cs
> +    private Stack<IMemento> History = new Stack<IMemento>();
1. Приватные поля используют lowerCamelCase (см. ссылку и скрин выше). Обрати внимание, что публичные, наоборот, используют PascalCase. Не надо, как Стас, судорожно заменять вообще все поля.
2. Для всех открываемых файлов одна и та же история. Демонстрация вероятно некорректной работы: [тык](https://drive.google.com/file/d/11dthLhSeLmXnu7gOiNvxf5hkmYOXZEjD/view?usp=sharing). Так и задумано? Всё же мне кажется, что в работе подразумевается сохранение состояния файла, а не редактора. Тогда стоит создавать не TextEditorMemento, а TextFileMemento. Тогда TextEditor вполне логично выступает в роли caretaker, и он будет всё также будет хранить историю. А у тебя всё намешано: интерфейс IMemento, который, по логике, должен называться IOriginator и имплементироваться, собственно, originator'ом, почему-то имплементирует memento. При этом сам originator, состояние которого ты сохраняешь, почему-то по совместительству является caretaker'ом и хранит стек своих состояний. Не надо так.

2024-02-28 15:07 UTC, KitovDanil commented on code.cs
> +            Content = History.Pop().GetState();
Допустим, история изменений выглядела так:
1. a
2. aa
3. aaa

Самым последним состоянием (которое в данный момент хранится и в Content) является "aaa". Мы выполняем 91 строчку, и в History запишется не "aa", а всё то же "aaa" ввиду того, как работает Stack.Pop(). Собственно undo, что и должна делать, по идее, эта строчка, не происходит. Единственное, что уменьшается история изменений, и она действительно теперь выглядит так:
1. a
2. aa

Надеюсь, понятно объяснил.

2024-02-28 16:14 UTC, circumstancesl commented on code.cs
> +    public TextFile(string FilePath)
Исправил

2024-02-28 16:14 UTC, circumstancesl commented on code.cs
> +        FilePath = FilePath;
Исправил

2024-02-28 16:14 UTC, circumstancesl commented on code.cs
> +        using (var Writer = new StreamWriter(FilePath))
Исправил

2024-02-28 16:14 UTC, circumstancesl commented on code.cs
> +    public void OpenFile(string FilePath)
Добавил исключение FileNotFoundException

2024-02-28 19:24 UTC, circumstancesl commented on code.cs
> +    private Stack<IMemento> History = new Stack<IMemento>();
Улучшил

2024-02-28 19:24 UTC, circumstancesl commented on code.cs
> +            Content = History.Pop().GetState();
Улучшил

2024-02-28 19:49 UTC, circumstancesl commented on code.cs
> +    public void Save(string FilePath)
Добавил

2024-02-29 01:53 UTC, KitovDanil requested changes

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +            using (var Writer = new BinaryWriter(File.Open(filePath, FileMode.Create)))
Локальная переменная в PascalCase.

Ниже аналогичная проблема.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +        var Files = Directory.GetFiles(directoryPath, "*.txt", SearchOption.AllDirectories);
Локальная переменная в PascalCase.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +    private Dictionary<string, List<string>> Index = new Dictionary<string, List<string>>();
Приватная переменная в PascalCase.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +        foreach (var FileUser in Files)
Локальная переменная в PascalCase.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +        Caretaker Caretaker = new Caretaker();
Здесь и ниже целый ряд локальных переменных в PascalCase.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +        using (var Writer = new StreamWriter(FilePath))
Не полностью. Оставлю новые комментарии.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +    public void OpenFile(string FilePath)
Где?

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +        Content = File.ReadAllText(filePath);
Не обработаны исключения.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +        Caretaker Caretaker = new Caretaker();
Также нехорошо, если название переменной совпадает с названием класса. Если исправишь стиль, то и эта проблема решится, но на будущее.

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +    public void Save(string filePath, bool useBinarySerialization)
Бинарная сериализация и десереализация написана - это хорошо. Но теперь новая проблема: они ни разу не используются :)

2024-02-29 01:53 UTC, KitovDanil commented on code.cs
> +    private Stack<Memento> history = new Stack<Memento>();
Максим, вот ты мне скажи, общая история для всех файлов это баг или фича? Я тебе даже видос записал, где я открываю файл2, делаю пару откатов, и оказывается, что в его истории оказывается контент файла1. Ты написал в ответе на мой коммент "Улучшил", но конкретно этот момент никак не изменился.

2024-02-29 05:19 UTC, circumstancesl commented on code.cs
> +    private Stack<Memento> history = new Stack<Memento>();
Это фича

2024-02-29 05:19 UTC, circumstancesl commented on code.cs
> +    private Stack<IMemento> History = new Stack<IMemento>();
Общая история - это фича

2024-02-29 12:30 UTC, circumstancesl commented on code.cs
> +        using (var Writer = new StreamWriter(FilePath))
Исправил

2024-02-29 12:31 UTC, circumstancesl commented on code.cs
> +    public void OpenFile(string FilePath)
Добавил исключение FileNotFoundException 121 строка

2024-02-29 12:31 UTC, circumstancesl commented on code.cs
> +            using (var Writer = new BinaryWriter(File.Open(filePath, FileMode.Create)))
Исправил

2024-02-29 12:31 UTC, circumstancesl commented on code.cs
> +        var Files = Directory.GetFiles(directoryPath, "*.txt", SearchOption.AllDirectories);
Исправил

2024-02-29 12:31 UTC, circumstancesl commented on code.cs
> +    private Dictionary<string, List<string>> Index = new Dictionary<string, List<string>>();
Исправил

2024-02-29 12:31 UTC, circumstancesl commented on code.cs
> +        foreach (var FileUser in Files)
Исправил

2024-02-29 12:31 UTC, circumstancesl commented on code.cs
> +        Caretaker Caretaker = new Caretaker();
Исправил

2024-02-29 12:32 UTC, circumstancesl commented on code.cs
> +        Content = File.ReadAllText(filePath);
Добавил исключение FileNotFoundException 121 строка

2024-02-29 13:04 UTC, circumstancesl commented on code.cs
> +    public void Save(string filePath, bool useBinarySerialization)
Реализовал в class program

2024-02-29 15:48 UTC, KitovDanil requested changes

2024-02-29 15:48 UTC, KitovDanil commented on code.cs
> +        Content = File.ReadAllText(filePath);
Кидать-то он их и сам умеет. Вопрос тут в том, что нет ни одного try-catch блока. И просмотри весь остальной код на предмет возможных исключений. При следующем ревью я зайду в твою программу и буду вместо пути до директории вводить "123", "C:/Us123er/Админ/Desktop" и прочее. Аналогичное для сохранения и чтения файлов, сериализация/десереализации и т.д.

2024-02-29 15:48 UTC, KitovDanil commented on code.cs
> +        foreach (var FileUser in files)
FileUser исправить на lowerCamelCase, т.к. локальная переменная. Аналогично для Content двумя строчками ниже, Entry и FileUser ещё несколько ниже.

2024-02-29 15:54 UTC, circumstancesl commented on code.cs
> +        foreach (var FileUser in files)
Исправил

2024-02-29 15:57 UTC, KitovDanil approved these changes

2024-02-29 15:57 UTC, merged